### PR TITLE
add index to hoofd_object field of Audittrail

### PR DESCRIPTION
**Pull request by annashamray**
Reason:
Every time `Audittrail resource` is requested for some object full scan of the table happens

### CODE REVIEW

**Comment by annashamray** [comment]
> Can we work https://stackoverflow.com/a/51880653 into the solution instead of defining custom SQL?
> 
> I don't like not having that index defined on the model and not uninstalling the index when reverse-migrating.

I tried to go this way - you can see it in the https://github.com/VNG-Realisatie/vng-api-common/pull/102/commits/2c0d8d0cf7c980feea5086469077c9f9d550cff2 commit, but it didn't work for Django==2.1

**Comment by sergei-maertens** [comment]
@annashamray all APIs should be on Django 2.2 by now (I upgraded them a while ago), so we can drop support for Django 2.0 and 2.1 :+1:

**Comment by annashamray** [comment]
> @annashamray all APIs should be on Django 2.2 by now (I upgraded them a while ago), so we can drop support for Django 2.0 and 2.1

Great news! I will when return to https://github.com/VNG-Realisatie/vng-api-common/pull/102/commits/6514419098273baf50a2959654296ba994b9df1d commit. I think that was the cleanest way to create this index

**Comment by joeribekker** [comment]
I want this in for 1.0 APIs as well as future versions.

**Comment by sergei-maertens** [comment]
Rebased so that backporting is easier

**Pull request merged**
