### PR TITLE
:sparkles: Add X-NLX-Logrecord-ID header

### PR DESCRIPTION
**Pull request by stevenbal**
issue: https://github.com/VNG-Realisatie/gemma-zaken/issues/1453

Should be linked to merging #152

### CODE REVIEW

**Comment by sergei-maertens** [comment]
I doubt that these headers even reach the backend service from the NLX inway. As far as I understand it, headers are stripped after the inway: https://docs.nlx.io/reference-information/transaction-log-headers

**Comment by stevenbal** [comment]
> I doubt that these headers even reach the backend service from the NLX inway. As far as I understand it, headers are stripped after the inway: https://docs.nlx.io/reference-information/transaction-log-headers

@sergei-maertens hmm, `X-NLX-Logrecord-ID` isn't included in the headers they mention that are stripped off before the request reaches the inway, but it indeed doesn't seem to mention whether or not the headers actually reach the backend application, so I'm not sure :thinking: 

The `X-NLX-Request-Application-Id` and `X-NLX-Request-User-Id` headers are apparently stripped away before the request even reaches the inway, so these can probably be removed from the code altogether?

**Comment by sergei-maertens** [comment]
yeah, I remember us asking the NLX team if they could keep those headers, but they didn't seem to be in favour for that.

I've also pinged you in the Common Ground slack #nlx channel - maybe you can try and get some information from the team directly on what gives.

**Comment by stevenbal** [comment]
Ah, I see that https://github.com/VNG-Realisatie/gemma-zaken/issues/1428 is about removing those old headers. I asked about the `X-NLX-Logrecord-ID` header specifically in the nlx slack channel, and it seems that this header should make it through to the backend.

**Comment by joeribekker** [comment]
@stevenbal waar wordt dit stuk van het issue getackled:

> Dit dient dus ook opgeslagen te worden in de auditlog.

**Review by joeribekker — CHANGES_REQUESTED** [review]
Mag naar stable/1.0.x

**Comment by joeribekker** [comment]
@stevenbal kan je deze PR combineren met #152? Ze moeten toch samen en anders zijn er db migratie issues en merge conflicts.

**Comment by stevenbal** [comment]
combined with https://github.com/VNG-Realisatie/vng-api-common/pull/152, closing this one

**Pull request closed without merging**
