### PR TITLE
:bug: view should return Response object

### PR DESCRIPTION
**Pull request by annashamray**

### CODE REVIEW

**Review by joeribekker — CHANGES_REQUESTED** [review]
Let's not do this as it might break other apps.

As far as I can tell, it's only used here: https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/blob/develop/src/zrc/api/viewsets.py#L232

So, the Zaken API uses the `SearchMixin` but doesn't even wrap the response. I do see it's used as "internal method" so you need to wrap the `get_search_output` anyway, like so:

```
@action(methods=("post",), detail=False)
    def _zoek(self, request, *args, **kwargs):
        search_input = self.get_search_input()
        # do stuff
        return self.get_search_output(queryset)
```

In there, you can wrap it as `Response`. I suggest closing this PR without merging and solving it your component.

**Comment by annashamray** [comment]
@joeribekker 
This method is used only if there is a search on geo-coordinates, which is implemented now only in Zaken API and Objects API
Zaken API doesn't wrap it because it has pagination and doesn't go to this line of code. 

I've fixed it in my component (Objects API), but I do think it's a bug because there is no consistency in the result, returned by this method. It could be now either ReturnList or Response object, which seems not correct for me.

**Comment by joeribekker** [comment]
> Zaken API doesn't wrap it because it has pagination and doesn't go to this line of code.
Why would pagination prevent this code from being reached? How else can the zoek-endpoint return any data?

> I've fixed it in my component (Objects API), but I do think it's a bug because there is no consistency in the result, returned by this method. It could be now either ReturnList or Response object, which seems not correct for me.

I don't see how it can switch between `ReturnList` and `Response`? Serializers always return a `ReturnList` or `ReturnDict`, but with `many=True`, it's always a `ReturnList` afaik.

I still think it's not a bug since you always need to wrap this function within an `@action` decorated function in your own viewset anyway. This is not done in the Zaken API which imo is the actual bug. In https://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing you see the response as always wrapped as a `Response`.

So, the question is do we want the Mixin to do it, or the Viewsets that uses this Mixin. It doesn't matter either way, as long as its clear on how to use this mixin.

I'll assign @sergei-maertens to make the final call.

**Comment by annashamray** [comment]
> Why would pagination prevent this code from being reached? How else can the zoek-endpoint return any data?

https://github.com/VNG-Realisatie/vng-api-common/blob/eee9dfb4becc22327a556a5f28298b64d696f0f7/vng_api_common/search.py#L25
It the view has pagination it will go to this part of the code, and the result would be Response object (since `self.get_paginated_response` returns Response)

If the view doesn't have pagination, the result would be ReturnList 


> I'll assign @sergei-maertens to make the final call.

I agree

**Review by joeribekker — APPROVED** [review]
Oh, i missed that. Well, that's definitly not good. So it either needs to be response or serializer data.

I think it's fine to return a `Response` in that case!

**Comment by sergei-maertens** [comment]
I agree with the discussion and the patch. Consistency in the return type is important, and there's no easy way around getting paginated non-response return value, so response object it is.

**Review by sergei-maertens — APPROVED** [review]

**Pull request merged**
